version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
      - pip install -r hello_world/requirements.txt
  build:
    commands:
      - sam build
      - sam package --s3-bucket my-pipeline-artifacts-bucket --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
