version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r hello_world/requirements.txt
  build:
    commands:
      - sam build
      - sam package --resolve-s3 --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml
