version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      # Nothing needed! Everything is pre-installed
       - echo "=== VERIFYING PRE-INSTALLED TOOLS ==="
       - aws --version    
       - sam --version    
       - python --version 
       - pip --version 

  build:
    commands:
      - sam build
      - sam package --resolve-s3 --output-template-file packaged.yaml
    

  post_build:
    commands:
      - echo "✅ Deployment complete!"